### ISSUE TITLE
WYWIWYG buttons overlapping content

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#157]
See http://support.inboundnow.com/support/topic/theme-specific-toolbar-buttons-overlap-text-editor/#lightbox/1/ for more details

**Comment by Mizagorn** [comment]
Current CSS on lines 13-15 of `\landing-pages\css\admin-post-edit.css`: 
```
.quicktags-toolbar, .wp_themeSkin tr.mceFirst td.mceToolbar {
	height: 38px;
}
```

Added CSS below that to override fixed-height quicktags toolbar styling. 
```
.quicktags-toolbar {
	height: auto;
}
```

Fixes extra toolbar buttons overlapping text area in both Visual and Text tab versions of the editor. I applied this to `admin-post-new.css` as well just in case.  Did not change styling for the other classes because I did not research where they are used.

Does not appear to be an issue with the CTA editors.

**Comment by atwellpub** [comment]
Great! Implemented these changes via the commit tagged above. In the future feel free to implement your changes via a merge request. That way the commit will be on your record.

http://docs.inboundnow.com/guide/contributing-inbound-now-codebase/

**Comment by Mizagorn** [comment]
Excellent.
My first time using Git - never had a need before. Thanks for the info link!
