### ISSUE TITLE
Verify tgmpa fix

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#178]
Please verify this fix on your live site: https://github.com/inboundnow/landing-pages/commit/fa462dd162e59842a52f5cdc026b3ba740abd13d

Latest code should have everything replaced into a new class(es)

**Comment by jrfnl** [comment]
Uh oh... sorry to butt in... one of the TGMPA devs here. May I ask what you are trying to achieve here ?

The way TGMPA is set up - by design - , it can be used by themes and plugins at the same time and will gather all the dependency information from the various sources in just one screen. With the changes you seem to be making now, you are breaking that design and the end-user could end up with several TGMPA screens, several TGMPA notices on the admin pages and totally confused... :crying_cat_face: 

We've seen one issue on the fatal error notice during the testing period and that turned out to be an incomplete/corrupted download, not an issue with the TGMPA library itself.

**Comment by DavidWells** [comment]
We updated the class like you suggested and it caused fatal errors across a wide number of users that had themes or plugins using an older version of the class.

A.k.a the class is currently not stable to use without forking it to our needs.

Yes the user will have 2 notification boxes if another theme/plugin uses TGMPA but there will not be any fatal errors.

We prefer the non fatal error route.

In the future, we plan on using the non forked version but need to be sure that its forward and backwards compatible.

**Comment by DavidWells** [comment]
@jrfnl this was one of the errors with 2 conflicting versions of the class: 

Fatal error: Call to undefined method TGM_Utils::validate_bool() in /home/hatnohat/hudsonatwell.co/wp-content/plugins/landing-pages6/libraries/class-tgm-plugin-activation.php

Here was another: http://support.inboundnow.com/support/topic/trouble-accessing-the-admin/ "Fatal error: Call to protected TGM_Plugin_Activation::__construct() from invalid context in...(theme class) "

**Comment by jrfnl** [comment]
@DavidWells Thanks for your response.

> Fatal error: Call to undefined method TGM_Utils::validate_bool() in /home/hatnohat/hudsonatwell.co/wp-content/plugins/landing-pages6/libraries/class-tgm-plugin-activation.php

This really indicates a corrupted download package. The `TGM_Utils` class was introduced in v 2.5.0 and is only called from code in v 2.5.0. All that code is in one file, so the only reason the class cannot be found can be a corrupted package. ([TGMPA/#421](https://github.com/TGMPA/TGM-Plugin-Activation/issues/421))

The only other thing I can think of is a completely different package also using the class name `TGM_Utils`, though that should be easy enough to find out if the user shares details about installed themes and plugins.
Would be a bit weird though... I've send a message to @thomasgriffin checking if he knows of any.

Gosh.. how I miss being able to use namespaces....

Anyway, if we would get confirmation that another theme/plugin/library is using that class name, we'll happily change the class name and release v 2.5.1 asap.

> "Fatal error: Call to protected TGM_Plugin_Activation::__construct() from invalid context in...(theme class) "

That is one we are also aware off ([TGMPA/#391](https://github.com/TGMPA/TGM-Plugin-Activation/issues/391)) and the constructor method was made private by design. This one happens when v 2.5.0 has been loaded in and another plugin or theme tries to load TGMPA <= 2.3.6 after that.
v 2.3.6 was released over three years ago and should most definitely not be used anymore. Unfortunately it seems it still is, more than we'd like to see.

This one is the reason why we've been trying to reach out to theme and plugin devs urging them to upgrade.

**Comment by jrfnl** [comment]
@DavidWells FYI - just did a quick search on the class name and to my dismay found another prominent WP plugin using the same classname. Mea Culpa.
Just send in PR [TGMPA/#446](https://github.com/TGMPA/TGM-Plugin-Activation/pull/446) for immediate release to fix that.

**Comment by DavidWells** [comment]
We are all for using the unaltered class.

We will revisit it in like 6months to see if compatibility is stable out in the wild.

Thanks for your guys work on the class. It's super nifty.

**Comment by jrfnl** [comment]
@DavidWells In six months time (well maybe a little longer), we hope to have abolished the need for the class: https://make.wordpress.org/core/2015/07/10/feature-plugin-chat-on-july-14/#comment-26310

**Comment by jrfnl** [comment]
@DavidWells Just one last question - can you give me some idea how many users is "across a wide number of users" ?
Even though I don't think it is the right way to go, I will discuss making the constructor public again - for the time being - to prevent that second fatal. That would eliminate your issues for now.

**Comment by DavidWells** [comment]
We had 5 reports and then pulled our latest push to stop the issue.

From what I can tell, it was a fatal for everyone not using the very very
latest 2.5.0 version of your class.

So I'd imagine the problem is going to be pretty widespread

**Comment by jrfnl** [comment]
Thanks for the reply.

FYI - The fatal will only occur if:
a) there is another theme/plugin also using TGMPA and
b) that one is loaded *after* TGMPA 2.5.0 has already been loaded (mu-plugins -> plugins -> themes)
b) that theme/plugin includes TGMPA <= 2.3.6.

There should be no problem whatsoever with TGMPA 2.4.0+ as long as people have implemented following the example.
We can't speak for non-standard implementations.

**Comment by jrfnl** [comment]
Will let you know if we decide to revert the making private of the constructor.

**Comment by jrfnl** [comment]
@DavidWells We've decided to revert the protected constructor.
I've also done some more incompatibility hunting and have just opened [TGMPA/PR #448](https://github.com/TGMPA/TGM-Plugin-Activation/pull/448) to fix it all.

I expect TGMPA 2.5.2 to be released today or tomorrow and I expect you should be ok to use the unaltered TGMPA again after that.

**Comment by atwellpub** [comment]
Hey guys we've a new conflict:
http://support.inboundnow.com/support/topic/fatal-error-on-subfolder-install-of-wp/#post-116084

**Comment by DavidWells** [comment]
Error message looks unrelated:

"Warning: require_once(/home/a6/Web/web/app/plugins/leads/shared/shortcodes/shortcodes-fields.php/wp-load.php): failed to open stream: No such file or directory in /home/a6/Web/web/app/plugins/leads/shared/shortcodes/shortcodes-fields.php on line 11

Fatal error: require_once(): Failed opening required ‘/home/a6/Web/web/app/plugins/leads/shared/shortcodes/shortcodes-fields.php/wp-load.php’ (include_path=’.:/usr/share/php:/usr/share/pear’) in /home/a6/Web/web/app/plugins/leads/shared/shortcodes/shortcodes-fields.php on line 11"

**Comment by atwellpub** [comment]
Sorry wrong support ticket:
https://wordpress.org/support/topic/fatal-error-cannot-redeclare-tgmpa_load_bulk_installer-1?replies=2#post-7264931

**Comment by DavidWells** [comment]
Weird there is a wrapper around that function:
https://github.com/inboundnow/landing-pages/blob/201708eff7a8de503bb0c49492eff9b67342d9b5/libraries/class-tgm-plugin-activation.php#L1870

We can rename it though, we are currently forked from that class and have
our own custom version

**Comment by atwellpub** [comment]
David another one here: 
https://wordpress.org/support/topic/landing-pages-caused-error?replies=1

Did I mess something up when I applied that security path? I am pretty sure I did everything correctly.

**Comment by DavidWells** [comment]
That function has been removed from our code and that entire class is forked under a new class name.

No sure why it would be throwing an error.

Unless tmpawhatevr function slipped back into the repo somehow
