### ISSUE TITLE
When ACF normal plugin installed + Activated

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#215]
There is a php warning thrown when ACF normal plugin activated (Version 4.4.3):

Notice: Undefined index: options in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/advanced-custom-fields/core/api.php on line 987

http://www.screencast.com/t/GQc2stb7iDG

Thought it was because an activation hook didn't run, but that wasn't it.

Any ideas?

**Comment by atwellpub** [comment]
I think it's because there are Pro fields defined in the wp instance and ACF lite doesn't like it. I have the same instance. Opened up an issue here:

https://github.com/elliotcondon/acf/issues/435

I think Elliot will have to code in a soft error handler. I might make a merge request. 

https://github.com/elliotcondon/acf/issues/435

**Comment by atwellpub** [comment]
Merge Request:
https://github.com/elliotcondon/acf/pull/438
