### ISSUE TITLE
Duplicated function lp_get_parent_directory() and inbound_get_parent_directory()

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#233]
The two functions `lp_get_parent_directory()` and `inbound_get_parent_directory()` are identical. Are we going to eliminate one of them?

**Comment by atwellpub** [comment]
We have to assume that lp_get_parent_directory() is being used by customer's custom template builds so we will always have to have it in as a legacy method. But since we are backing out of using either method and inbound_get_parent_directory is brand new and unused we can eventually remove it from /shared/. Let's leave it alone for now though.

**Comment by atwellpub** [comment]
See for more reference:
https://github.com/inboundnow/landing-pages/issues/232
https://github.com/inboundnow/landing-pages/issues/230
