### ISSUE TITLE
[acf] Acacia

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#236]
In the change below data_type is changed to 'acf' and the 'acf' sub key is removed per the new standards highlighted in this issue:
https://github.com/inboundnow/landing-pages/issues/216
##

**Comment by daprela** [comment]
Will we leave the scripts (css and js) enqueued inside the html in the traditional way in this templates, or should I enqueue scripts the WordPress way, with the enqueue hook? Using the hook complicates things but it's the 'canonical' way

**Comment by daprela** [comment]
@atwellpub @DavidWells 
All of the sections in the template are working now. Needs further testing to fix a few issues that in my opinion come from ACF integration.
The hero box needs to be fixed. I will try to replace image and oEmbed fields with a wysiwyg because it's not possible to control the size of the video in the oEmbed field (a fixed size would be bad for responsiveness, and I cannot add a size in %). Right now, I'm leaving this oEmbed to allow studying the problem with conditional logic (issue #237 )

**Comment by daprela** [comment]
Please also look at how I 'solved' the problem of adding the font awesome icons in the three columns section. This is meant to be a temporary solution while we look for a better method

**Comment by atwellpub** [comment]
>>Will we leave the scripts (css and js) enqueued inside the html in the traditional way in this >>templates, or should I enqueue scripts the WordPress way, with the enqueue hook? Using the hook >>complicates things but it's the 'canonical' way

When index.php loads it's being loaded in the template_redirect hook, which loads before wp_enqueue_scripts. So I think we can use the WordPress way, but it might read easier for template developers to see us call in the old way via inline PHP. 

One reason to use the canonical way is to prevent rare script conflicts. Maybe there is another with header/footer script placements and it let's them be unhooked/unregistered.

I personally think it will be confusing to the inline feel of index.php and might discourage understanding of the template build process. What do you think?

**Comment by atwellpub** [comment]
One thing I notice is that the URL fields are not accepting a # due to field validation issues. We might should change the field type to text to let the # slide.

**Comment by atwellpub** [comment]
>>>Please also look at how I 'solved' the problem of adding the font awesome icons in the three columns section. This is meant to be a temporary solution while we look for a better method. 

I think it's fine for now. Looks great.

**Comment by DavidWells** [comment]
For font awesome we need to include this field in our code https://wordpress.org/plugins/advanced-custom-fields-font-awesome/ .

Adding the class is not very user friendly.

We are going to be using 'custom' advanced custom field inputs in the future and we might as well start with this one.

See: http://plugins.svn.wordpress.org/advanced-custom-fields-font-awesome/trunk/acf-font-awesome-v5.php for how it's integrated with acf 5

**Comment by atwellpub** [comment]
Font awesome field support is now in:
https://github.com/inboundnow/landing-pages/issues/217

**Comment by daprela** [comment]
Adding media to the template is a pain. If I use a wysywig field then I cannot have any control over the size of what it's added. Basically it means that the person that adds the media must take care of the size aspect.
If I use the image/video fields with the conditional logic, then I can control the size of the image with a `max-width:100%;` but I cannot control the video size, that comes out too small. If I setup the video size as a field property in the ACF editor it cannot be changed afterwards, and we lose responsiveness. Unofrtunately, ACF doesn't allow me to set the video size as a percentage.

At this point, I really don't know what's best, do you think that users can manage the size of the media by themselves?

**Comment by daprela** [comment]
>One thing I notice is that the URL fields are not accepting a # due to field validation issues. We might >should change the field type to text to let the # slide. 

I've added http://# as predefined value, that should be enough. The strange thing is that in the email templates the url field always accepted the # as url

**Comment by daprela** [comment]
I've enqueued scripts and styles at the top if index.php. the template works perfectly. Please take a look and let me knowif you want this be the standard way for future templates.

**Comment by daprela** [comment]
Added the new custom font awesome custom field. It works beautifully, I didn't even have to modify the index.php file.
The field has an option that allows me to let the plugin enqueue automatically fontawesome. I've let the option off for now, let me know if you want to enable it.

I've also found this plugin https://wordpress.org/plugins/acf-google-font-selector-field/ in case we want to use it somewhere

**Comment by atwellpub** [comment]
>Adding media to the template is a pain. If I use a wysywig field then I cannot have any control over the size of what it's added. Basically it means that the person that adds the media must take care of the size aspect.

>If I use the image/video fields with the conditional logic, then I can control the size of the image with a max-width:100%; but I cannot control the video size, that comes out too small. If I setup the video size as a field property in the ACF editor it cannot be changed afterwards, and we lose responsiveness. Unfortunately, ACF doesn't allow me to set the video size as a percentage.

>At this point, I really don't know what's best, do you think that users can manage the size of the media by themselves?

Is there a need for the video to have different percentage sizes? If there is not than we can hard code the width into the template's CSS. If so then we can have a text field and use instructions to tell the people to input the correct percentage and then use that acf text field value in the template. I also recommend opening an issue over here to help improve ACF: 
https://github.com/elliotcondon/acf

 > I've enqueued scripts and styles at the top if index.php. the template works perfectly. Please take a look and let me knowif you want this be the standard way for future templates.

I notice wp_head action hook is firing before the files are being enqueued. Is this ok? It may be forcing scripts to load via wp_footer, wwhere wp_enqueue_scripts provide the users an option to load in wp_head or wp_footer. We might want wp_head to fall after the enqueue. Otherwise I like the way it looks. It looks very clean.

**Comment by daprela** [comment]
>Is there a need for the video to have different percentage sizes? If there is not than we can hard code the width into the template's CSS.
I don't need different percentage sizes, just a `width: 100%;` would do the job, the problem is that both width and height are hardcoded as inline styles in the iframe element. I can override them into the template's CSS but if I set both width and height to 100% the video will come out distorted. Forcing the height to auto with !important doesn't work. If you have a solution to get rid of the height property I'm happy to implement it.

>I notice wp_head action hook is firing before the files are being enqueued. Is this ok? It may be forcing scripts to load via wp_footer, wwhere wp_enqueue_scripts provide the users an option to load in wp_head or wp_footer. We might want wp_head to fall after the enqueue. Otherwise I like the way it looks. It looks very clean.
You are right, I forgot this detail. I've moved wp_head after the enqueue function.

**Comment by DavidWells** [comment]
The template is good for now.

It's looking great!

Move on to the next: https://trello.com/c/MXvcX8Al/56-template-template-2

I will have a look at the video/media stuff. I've done some responsive
video stuff in the past

**Comment by daprela** [comment]
Please check the template again. Thanks to a small jquery function the user can determine height and width of the video. Default is 500x300

**Comment by atwellpub** [comment]
Nice! Looks great really.

**Comment by atwellpub** [comment]
Should we valign the header top? 
![](http://content.screencast.com/users/adbox/folders/Jing/media/d05bb1b5-4cd1-4734-9cb8-ec4b0c4a48d7/2015-09-18_1945.png)

**Comment by DavidWells** [comment]
Instead of vertical aligning the text, we can vertically center the video/image.

See: http://zerosixthree.se/vertical-align-anything-with-just-3-lines-of-css/

**Comment by daprela** [comment]
@atwellpub The reason why the text is not correctly vertically aligned is that the header has a padding above it. That padding becomes necessary when the media queries are triggered, and the box on the right must be re-positioned below the video. I got rid of the padding now by adding a media query that triggers the padding only when the two boxes are stacked vertically. The effect is much better. This is necessary even if I valign the elements with David's technique

@DavidWells The technique of vertical align is beautiful but if used on two divs horizontally aligned it breaks the responsiveness. The problem is that for this to work the container must have the height explicitly set (even height:100% works, so you don't have to know the height of the element but fact you know the height of the container of the element). Setting the height of the two divs to 100% triggers a cascading effect where I must change a number of other styles.
I've added the effect, and moved some styles to a couple of media queries in order to keep the responsiveness of the template. It has taken some time in order to test that everything works properly. It seems that it works, try to give it a look yourself

**Comment by atwellpub** [comment]
Looks good to me. All that seems to be left is the call to action section now:


![](http://content.screencast.com/users/adbox/folders/Jing/media/2605f7da-c396-4bc6-8d76-c72ef3d8676a/2015-09-21_1353.png)

**Comment by DavidWells** [comment]
Yeah for the form areas, the form styles will need to apply to a form with inbound-now fields.

This is the trickiest part of creating templates.

@daprela so create an inbound-form with all possible fields and see what the output looks like in that section ( and the others, because users will put forms anywhere there is a wysiwyg or text field )

Once we have some base CSS for the the inbound-forms to look nice in bootstrap it should probably work with all the templates we are building. ( who knows, they might look nice out of the box =)

**Comment by daprela** [comment]
@atwellpub I've added an optional header and also added color options for the testimonials text and name that was missing before. One could give different colors to different testimonials, maybe it's too much flexibility, I don't know, I thought it could be an interesting option.
The slider color cannot be changed because for technical reason it must stay in the bootstrap CSS. To solve issues of low contrast with light backgrounds I've given it a black border, so either that or the white background will be visible.

Now I will start studying the form problem

**Comment by atwellpub** [comment]
Changes look good. +1

**Comment by atwellpub** [comment]
@daprela 

Any reason why this plugin would not be compatible with Acacia? We use wp_head(), why wouldn't the scripts enqueue I wonder. 

https://github.com/wp-plugins/use-any-font
http://support.inboundnow.com/support/topic/changing-font/

**Comment by daprela** [comment]
To me, it's already a mystery why the standard enqueue hook doesn't work in our templates. I'll try to run some tests bot honestly I'm not sure what to do here

**Comment by atwellpub** [comment]
Hey if you setup a quick test see if wp_print_scripts(); makes a difference. It feels like we've already been over this though.

**Comment by daprela** [comment]
Yes, we've been over every possible tests before using wp_head()

**Comment by daprela** [comment]
There's no way to make the hook `wp_enqueue_scripts` work. Also, re. wp_print_scripts() look at this, Andrew Nacin in person writes: https://make.wordpress.org/core/2011/12/12/use-wp_enqueue_scripts-not-wp_print_styles-to-enqueue-scripts-and-styles-for-the-frontend/

Now, thinking again about it, the only reason for the hook to not work in my opinion is that the template is added AFTER the hook is already run. Could that even be possible?

**Comment by atwellpub** [comment]
We load the template at the template_redirect hook, which runs before the wp_head hook:
https://codex.wordpress.org/Plugin_API/Action_Reference/template_redirect

Just an FYI. I'm not sure you or I will be able to solve this,, Know where to go from here?

**Comment by daprela** [comment]
I'm not optimistic but trying to understand what could be the source of the problem. this is the order in which the hooks run
- template_redirect 	
- get_header 	
- wp_enqueue_scripts 	
- wp_head

`wp_enqueue_scripts` enqueues the js script files but not the css files (I remember this from my earlier tests) which suggests that it enqueues the css before the template starts loading. Instead, wp_head will probably run after the template has finished loading. This could explain why often when I load a template in the frontend I see the content layout broken at first, and only after a few seconds everything goes at its places.
This page in the codex explicitly suggests to not use template_redirect to load templates but to use  the `template_include` filter. https://codex.wordpress.org/Plugin_API/Action_Reference/template_redirect

Our problems with the wp_enqueue_scripts hook could be generated by the incorrect use of that action hook. Have you ever considered using the `template_include` filter instead of `template_redirect`?

**Comment by atwellpub** [comment]
Let's give it a test. I'll see if they are inter changable.

**Comment by atwellpub** [comment]
I was mistaken we use the single_template  filter hook. I changed over though. The landing pages still load. Does it fix it?

**Comment by daprela** [comment]
No, the problem is still there. In my opinion the enqueue hook is used in the wrong place. It runs too late, it should be loaded at the plugin load along with all other hooks but this would mean to think a completely different mechanism

**Comment by atwellpub** [comment]
But the enqueues here in this plugin are hooked into at plugins_init:
https://github.com/wp-plugins/use-any-font

**Comment by daprela** [comment]
Yes, you are right but I'm trying to understand why the hook `wp_enqueues_scripts` doesn't work in our templates. In my opinion that's important because it tells us that there's something wrong in the way we load templates, and maybe fixing this problem would also fix the problem with the Use Any Fonts plugin, and would prevent future problems too.

I have an idea and need to experiment with it. I will work on it in my free time, it will be a good way to learn how the plugin works.
