### ISSUE TITLE
Always set default images for options

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/landing-pages#243]
http://www.screencast.com/t/HduubyaYwrY

Also in the description field of the image give the original dimenions of the image to help the user.

Example: "Use an image with the dimensions 200x200 pixels"

**Comment by atwellpub** [comment]
I'm not sure if we can set default repeater field images. Might be good, time saving solution to make the field required instead. 

* [ ] Make repeater image subfield required
* [ ] Add subfield description to control width.

**Comment by atwellpub** [comment]
At the moment we can't set default values for images unless we find out a way to upload them programmatically to the media uploader and return the gallery id instead of the image URL:

https://github.com/elliotcondon/acf/issues/449

This is even more difficult to do with repeaters. I believe we are still in discussion on how to automatically populate repeater field rows with default content, though I am having trouble finding the discussion issue. 

Should we give this a shot?

**Comment by DavidWells** [comment]
We can just use conditional logic to use the default images associated with the templates.

```php

if($repeaterImage){
// use it
} else {
// use default image from template files
}

```
