### ISSUE TITLE
In Triumph landing page, $header_logo returns false

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#249]
The field $header_logo is a normal field (no repeater no flexible etc.) that is set to return the url of the image. Instead, it returns false

https://github.com/inboundnow/landing-pages/blob/master/templates/triumph/index.php#L76

**Comment by atwellpub** [comment]
This looks to be working after the latest change. I hope this change doesn't break any other  templates.  Will you report them here if they do? 

I tried to get a default_value in for this but am not able to have a URL for an image field type with ACF Pro because the return formatting ends up returning a blank value instead of the default_value URL.

**Comment by daprela** [comment]
acf does not support default value for images, I suppose this is why you're struggling with this

**Comment by atwellpub** [comment]
Opened an issue here to see what we can do:
https://github.com/elliotcondon/acf/issues/449
