### ISSUE TITLE
Three Column Lander

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#254]
This is not a true responsive template. Would like to figure out how to make it responsive. 

http://demo.inboundnow.com/3-column-lander/

**Comment by daprela** [comment]
What do you think it's missing to be truly responsive? We could stack the three columns instead of adding the 'more' menus

**Comment by DavidWells** [comment]
We need to tread carefully around the free templates being responsive.

It's a primary reason for people to upgrade to get responsive templates

An idea I'd put forward is having free templates as is (but more of them) with pro counterparts with responsiveness (plus other features)

**Comment by atwellpub** [comment]
I'd like all our core templates to be responsive because we are to a point in the internet where non responsive design is bad design. Even our basic free templates shouldn't fall into the bad design category. 

I think all of our free templates are responsive besides this one. Not sure though. 

@daprela 

Yeah the columns would have to stack perfectly on window resize and the center content section would need to have overspilt content revealed. Right now if center content goes over window size (vertically) then the spill over is hidden.

**Comment by atwellpub** [comment]
http://support.inboundnow.com/support/topic/the-scrollbar-doesnt-work/

**Comment by daprela** [comment]
I think that I will make it with Bootstrap. Making templates truly responsive is a long work if you do it from scratch, there are too many variables involved. Bootstrap gives hundreds of hours of development and testing. I will give this issue priority 1 as soon as I come back

**Comment by daprela** [comment]
The conversion is finished, now the template is 100% responsive. I've also added the styling for inbound forms.
The template is made so that the three columns are stacked up in small screens with the main column on top.
Please check it out and let me know, if you approve it I will then clean the template by eliminating all the code and styling that have been commented out

**Comment by atwellpub** [comment]
Looking good. Can we have the columns span the entire height while still being responsive? 

http://screencast.com/t/6PkzPZOMIMWx

Also, can we set boottrap in /shared/assets/includes/BootStrap/ and source the enqueue from there? Bootstrap is a nice tool to use here and there and it would probably do better in shared than included with the template.

**Comment by daprela** [comment]
I'm sorry for that, it was supposed to span the entire height since the beginning, and I've spent a lot of time searching and testing the solution to get that result. It should work now.

I agree about Bootstrap. I would also open a discussion about including other functions like HexToHsl and HexToRgb in the shared folder. These are general utility functions that can be used across a number of templates, and more could be added in future. We could add them under shared/functions inside the shared.php file, or have each function in its own file to minimize the amount of code included and avoid including ten functions when you need only one

**Comment by DavidWells** [comment]
Please work on the premium templates and pause work on the free stuff after
you fix this issue

**Comment by daprela** [comment]
Travis is failing after my last update. It seems that the problem is unrelated to my modifications (I just changed a few styles). This is what triggers the error, taken from this page https://travis-ci.org/inboundnow/landing-pages/jobs/83814541

Fatal error: require(): Failed opening required '/var/www/inboundtesting.dev/wp-content/plugins/landing-pages/vendor/lucatume/wp-browser/src/WPBrowserMethods.php' (include_path='.:/home/travis/.phpenv/versions/5.4.37/pear:/home/travis/.phpenv/versions/5.4.37/share/pyrus/.pear/php') in /var/www/inboundtesting.dev/wp-content/plugins/landing-pages/assets/tests/codeception/_bootstrap.php on line 9

I don't see any vendor folder, and I don't see that it's been removed recently either, what is going on here?

**Comment by atwellpub** [comment]
It's going to take me a moment to investigate, setting up a new laptop. We should be ok though since the commit doesn't seem to change anything.

**Comment by atwellpub** [comment]
Three column lander looks great, thank you Giulio!
