### ISSUE TITLE
[acf] Pure

### ISSUE THREAD

**Issue by daprela** [inboundnow/landing-pages#259]
Assuming that the other landing pages are ok, I'm going to start working on this one now

**Comment by DavidWells** [comment]
Yeah lets keep moving through the templates.

We have a lot more to go. (like 20 more)

**Comment by daprela** [comment]
Pure landing page added, please check it out.

@DavidWells I need more templates, the template #8 on Trello is marked as paused and there's nothing else there. Don't worry about commenting the template on invision, now I got how the system works. If you need some time to put them together, I will stop working tomorrow and work full time some other day to make it up

**Comment by atwellpub** [comment]
Heya Guilio looking good. 

Noticed a few things:
* Seeing some soft errors relating to the content area title and it's arrow button.
* There's a content title section but doesn't seem to be a content section for the content area. If that's meant to be the case we might should change the name of the repeater to 'Content Spacer' rather than 'Content Area'.
* Questions about styling within the Inbound Form area.

http://screencast.com/t/D2ivbD7yCyk

**Comment by daprela** [comment]
* I fixed the soft error
* Changed the name of the content area to content spacer
* I suggest keep the discussion on the Ambrosia template issue for the form styling https://github.com/inboundnow/landing-pages/issues/266#issuecomment-150153623

**Comment by atwellpub** [comment]
looks good.
