### ISSUE TITLE
[doc request] How to create landing page templates using ACF

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#272]
@DavidWells 
@daprela 

Hey which one of you would like to draw this one up? 

Related support request:
http://support.inboundnow.com/support/topic/landing-page-custom-development/

**Comment by daprela** [comment]
Since I'm doing the templates, I'm supposed to be the expert :smile: 

I think that we should document the process for landing pages and email

How should I proceed? Will you create an account for me on the Inbound website?

**Comment by DavidWells** [comment]
We need the docs written in markdown much like: https://github.com/inboundnow/leads/blob/master/shared/docs/analytics.events.md

Then the docs can live in the tool and we can serve them to people from within the tool

**Comment by DavidWells** [comment]
Also see existing ACF tutorials https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#safe=active&q=acf%20tutorials and see what we can either link to or just grab and use

**Comment by DavidWells** [comment]
Just to clarify, add the markdown doc here: https://github.com/inboundnow/cta/tree/master/shared/docs just name it templating.md or something for now

**Comment by atwellpub** [comment]
@daprela 

If you write the doc in the way David has requested, I will convert it to publish on docs.inboundnow.com since that is where customers currently go to discover their information. That way both avenues can be satisfied. 

We do not have the resources atm to convert all our docs over to the system David desires. But developing this doc in markdown format is a good place to begin, and in the near future we can begin moving legacy docs to the new system. 

@DavidWells would you agree with this?

**Comment by DavidWells** [comment]
I have a plugin that converts markdown to Wordpress HTML.

We really don't want any docs in Wordpress because it's clunky to manage and has no version control.

But yeah We can migrate over to markdown with the old stuff eventually

**Comment by daprela** [comment]
I've published a first version of the guide in the dev branch https://github.com/inboundnow/landing-pages/blob/develop/shared/docs/how.to.create.landing.page.templates.using.ACF.md

Please check it out and feel free to leave your comments to improve it

**Comment by atwellpub** [comment]
Beautiful. 

I also have it here, but I am redirecting directly to md instead of trying to import markdown into wordpress manually. 

http://docs.inboundnow.com/guide/how-to-create-landing-page-templates-using-acf/

**Comment by atwellpub** [comment]
@daprela I noticed docs were added to shared in landing pages repo. I'm moving it over to cta bc we always have to treat cta's shared as the master and assume the others will be overwritten.

**Comment by daprela** [comment]
Thank you for telling me, it seemed logical to add the document to the landing page repo since the guide is for landing pages. I'll keep that in mind for the future

**Comment by JordanChoo** [comment]
@daprela thanks for creating an updated version of the documentation.

I went through the [tutorial links that you provided](https://github.com/inboundnow/landing-pages/blob/develop/shared/docs/how.to.create.landing.page.templates.using.ACF.md#intro) for getting to know ACF as I've never used it before. It seems that all the resources are for direct ACF plugin users rather than developers looking to integrate ACF pragmatically. 

I was hoping you could update that section with the relevant resources for someone like me just getting started?

If you need any help on my end please let me know. 

P.S. Would be great to know which version of ACF InboundNow is using as well.

**Comment by JordanChoo** [comment]
Also I think it would be easier from a reader's perspective to link directly to the [specific documentation relating to registering fields](http://www.advancedcustomfields.com/resources/register-fields-via-php/) in ACF via PHP rather than ACF's documentation home page.

**Comment by JordanChoo** [comment]
As a follow up question, from my understanding ACF Pro is now required in order to use the premium InboundNow and create custom themes (assuming you're using the repeater fields and flexible fields). What does that mean for individuals who are using a non-premium version of InboundNow but purchase a theme from the marketplace that requires ACF Pro?

**Comment by atwellpub** [comment]
@JordanChoo 

ACF Pro allows us to ship it's core with a premium template, which means for non Pro users that buy templates we will ship a 'helper extension' that is required to operate the template, which will essentially be a ACF Pro engine for the WordPress instance.

**Comment by daprela** [comment]
Hi @JordanChoo 
Thank you for your interest in my guide and in our plugins.
There are two reasons why I didn't include any links to guides to integrate ACF in your own plugin. The first is that it is out of the scope of my guide to teach it. The InboundNow suite has already ACF integrated, and that is transparent to you. The other reason is that there isn't any tutorial, guide or article about integrating ACF in your own plugin. At least, I haven't been able to find any. The classic way of integrating a third party plugin in your own is to add the plugin in a sub-directory called, for example, vendor, and then include its main file from inside your own plugin. This is exactly what you can do with the ACF plugin, and we do too. However, we add another layer in our plugin: by using the filter hook `acf/load_value` we intercept the load of custom fields, perform a check of the type of field required, and 'clean' the value. Cleaning means that for example some fields are returned as arrays even if they contain one value only. We remove the array and return the simple value. This reduces the amount of code inside every template because we have the values ready to be used. If you want to learn which hooks we use and how we integrate ACF in our plugin my advice is to look into the file `class.acf-integration.php` starting from the function `load_hooks()` where you can learn which hooks we use. As always, te best way to learn to code is to look into other people's code :smile:
